apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alchemy-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  selector:
    matchLabels:
      pv: alchemy-pv

