apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  labels:
    pv: alchemy-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: localhost
    path: "/data/testmount"

      
