apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: 2020-01-02T14:58:33Z
  name: test
  namespace: default
  resourceVersion: "423800"
  selfLink: /api/v1/namespaces/foo/serviceaccounts/test
  uid: 58796b34-2d70-11ea-8a57-001c25a0d18a
secrets:
- name: test
